// Code generated by ent, DO NOT EDIT.

package expert

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the expert type in the database.
	Label = "expert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldNameZh holds the string denoting the name_zh field in the database.
	FieldNameZh = "name_zh"
	// FieldNameEn holds the string denoting the name_en field in the database.
	FieldNameEn = "name_en"
	// FieldNameRu holds the string denoting the name_ru field in the database.
	FieldNameRu = "name_ru"
	// FieldNameKk holds the string denoting the name_kk field in the database.
	FieldNameKk = "name_kk"
	// FieldContentZh holds the string denoting the content_zh field in the database.
	FieldContentZh = "content_zh"
	// FieldContentEn holds the string denoting the content_en field in the database.
	FieldContentEn = "content_en"
	// FieldContentRu holds the string denoting the content_ru field in the database.
	FieldContentRu = "content_ru"
	// FieldContentKk holds the string denoting the content_kk field in the database.
	FieldContentKk = "content_kk"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// Table holds the table name of the expert in the database.
	Table = "expert"
)

// Columns holds all SQL columns for expert fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStatus,
	FieldSort,
	FieldNameZh,
	FieldNameEn,
	FieldNameRu,
	FieldNameKk,
	FieldContentZh,
	FieldContentEn,
	FieldContentRu,
	FieldContentKk,
	FieldCoverURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort uint32
)

// OrderOption defines the ordering options for the Expert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// ByNameZh orders the results by the name_zh field.
func ByNameZh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameZh, opts...).ToFunc()
}

// ByNameEn orders the results by the name_en field.
func ByNameEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameEn, opts...).ToFunc()
}

// ByNameRu orders the results by the name_ru field.
func ByNameRu(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameRu, opts...).ToFunc()
}

// ByNameKk orders the results by the name_kk field.
func ByNameKk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameKk, opts...).ToFunc()
}

// ByContentZh orders the results by the content_zh field.
func ByContentZh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentZh, opts...).ToFunc()
}

// ByContentEn orders the results by the content_en field.
func ByContentEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentEn, opts...).ToFunc()
}

// ByContentRu orders the results by the content_ru field.
func ByContentRu(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentRu, opts...).ToFunc()
}

// ByContentKk orders the results by the content_kk field.
func ByContentKk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentKk, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}
