// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-member-rpc/ent/medicalrecord"
)

// MedicalRecordCreate is the builder for creating a MedicalRecord entity.
type MedicalRecordCreate struct {
	config
	mutation *MedicalRecordMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (mrc *MedicalRecordCreate) SetCreatedAt(t time.Time) *MedicalRecordCreate {
	mrc.mutation.SetCreatedAt(t)
	return mrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableCreatedAt(t *time.Time) *MedicalRecordCreate {
	if t != nil {
		mrc.SetCreatedAt(*t)
	}
	return mrc
}

// SetUpdatedAt sets the "updated_at" field.
func (mrc *MedicalRecordCreate) SetUpdatedAt(t time.Time) *MedicalRecordCreate {
	mrc.mutation.SetUpdatedAt(t)
	return mrc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableUpdatedAt(t *time.Time) *MedicalRecordCreate {
	if t != nil {
		mrc.SetUpdatedAt(*t)
	}
	return mrc
}

// SetPatientName sets the "patient_name" field.
func (mrc *MedicalRecordCreate) SetPatientName(s string) *MedicalRecordCreate {
	mrc.mutation.SetPatientName(s)
	return mrc
}

// SetNillablePatientName sets the "patient_name" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillablePatientName(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetPatientName(*s)
	}
	return mrc
}

// SetPhoneNumber sets the "phone_number" field.
func (mrc *MedicalRecordCreate) SetPhoneNumber(s string) *MedicalRecordCreate {
	mrc.mutation.SetPhoneNumber(s)
	return mrc
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillablePhoneNumber(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetPhoneNumber(*s)
	}
	return mrc
}

// SetGender sets the "gender" field.
func (mrc *MedicalRecordCreate) SetGender(i int32) *MedicalRecordCreate {
	mrc.mutation.SetGender(i)
	return mrc
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableGender(i *int32) *MedicalRecordCreate {
	if i != nil {
		mrc.SetGender(*i)
	}
	return mrc
}

// SetAge sets the "age" field.
func (mrc *MedicalRecordCreate) SetAge(i int32) *MedicalRecordCreate {
	mrc.mutation.SetAge(i)
	return mrc
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableAge(i *int32) *MedicalRecordCreate {
	if i != nil {
		mrc.SetAge(*i)
	}
	return mrc
}

// SetVisitTime sets the "visit_time" field.
func (mrc *MedicalRecordCreate) SetVisitTime(i int64) *MedicalRecordCreate {
	mrc.mutation.SetVisitTime(i)
	return mrc
}

// SetNillableVisitTime sets the "visit_time" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableVisitTime(i *int64) *MedicalRecordCreate {
	if i != nil {
		mrc.SetVisitTime(*i)
	}
	return mrc
}

// SetDiagnosis sets the "diagnosis" field.
func (mrc *MedicalRecordCreate) SetDiagnosis(s string) *MedicalRecordCreate {
	mrc.mutation.SetDiagnosis(s)
	return mrc
}

// SetNillableDiagnosis sets the "diagnosis" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableDiagnosis(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetDiagnosis(*s)
	}
	return mrc
}

// SetTreatmentPlan sets the "treatment_plan" field.
func (mrc *MedicalRecordCreate) SetTreatmentPlan(s string) *MedicalRecordCreate {
	mrc.mutation.SetTreatmentPlan(s)
	return mrc
}

// SetNillableTreatmentPlan sets the "treatment_plan" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableTreatmentPlan(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetTreatmentPlan(*s)
	}
	return mrc
}

// SetPrescription sets the "prescription" field.
func (mrc *MedicalRecordCreate) SetPrescription(s string) *MedicalRecordCreate {
	mrc.mutation.SetPrescription(s)
	return mrc
}

// SetNillablePrescription sets the "prescription" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillablePrescription(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetPrescription(*s)
	}
	return mrc
}

// SetExaminationResults sets the "examination_results" field.
func (mrc *MedicalRecordCreate) SetExaminationResults(s string) *MedicalRecordCreate {
	mrc.mutation.SetExaminationResults(s)
	return mrc
}

// SetNillableExaminationResults sets the "examination_results" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableExaminationResults(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetExaminationResults(*s)
	}
	return mrc
}

// SetDoctorAdvice sets the "doctor_advice" field.
func (mrc *MedicalRecordCreate) SetDoctorAdvice(s string) *MedicalRecordCreate {
	mrc.mutation.SetDoctorAdvice(s)
	return mrc
}

// SetNillableDoctorAdvice sets the "doctor_advice" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableDoctorAdvice(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetDoctorAdvice(*s)
	}
	return mrc
}

// SetDoctorID sets the "doctor_id" field.
func (mrc *MedicalRecordCreate) SetDoctorID(s string) *MedicalRecordCreate {
	mrc.mutation.SetDoctorID(s)
	return mrc
}

// SetNillableDoctorID sets the "doctor_id" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableDoctorID(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetDoctorID(*s)
	}
	return mrc
}

// SetDepartment sets the "department" field.
func (mrc *MedicalRecordCreate) SetDepartment(s string) *MedicalRecordCreate {
	mrc.mutation.SetDepartment(s)
	return mrc
}

// SetNillableDepartment sets the "department" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableDepartment(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetDepartment(*s)
	}
	return mrc
}

// SetAppointmentID sets the "appointment_id" field.
func (mrc *MedicalRecordCreate) SetAppointmentID(s string) *MedicalRecordCreate {
	mrc.mutation.SetAppointmentID(s)
	return mrc
}

// SetNillableAppointmentID sets the "appointment_id" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableAppointmentID(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetAppointmentID(*s)
	}
	return mrc
}

// SetRemarks sets the "remarks" field.
func (mrc *MedicalRecordCreate) SetRemarks(s string) *MedicalRecordCreate {
	mrc.mutation.SetRemarks(s)
	return mrc
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableRemarks(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetRemarks(*s)
	}
	return mrc
}

// SetUserID sets the "user_id" field.
func (mrc *MedicalRecordCreate) SetUserID(s string) *MedicalRecordCreate {
	mrc.mutation.SetUserID(s)
	return mrc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableUserID(s *string) *MedicalRecordCreate {
	if s != nil {
		mrc.SetUserID(*s)
	}
	return mrc
}

// SetID sets the "id" field.
func (mrc *MedicalRecordCreate) SetID(u uuid.UUID) *MedicalRecordCreate {
	mrc.mutation.SetID(u)
	return mrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mrc *MedicalRecordCreate) SetNillableID(u *uuid.UUID) *MedicalRecordCreate {
	if u != nil {
		mrc.SetID(*u)
	}
	return mrc
}

// Mutation returns the MedicalRecordMutation object of the builder.
func (mrc *MedicalRecordCreate) Mutation() *MedicalRecordMutation {
	return mrc.mutation
}

// Save creates the MedicalRecord in the database.
func (mrc *MedicalRecordCreate) Save(ctx context.Context) (*MedicalRecord, error) {
	mrc.defaults()
	return withHooks(ctx, mrc.sqlSave, mrc.mutation, mrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mrc *MedicalRecordCreate) SaveX(ctx context.Context) *MedicalRecord {
	v, err := mrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrc *MedicalRecordCreate) Exec(ctx context.Context) error {
	_, err := mrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrc *MedicalRecordCreate) ExecX(ctx context.Context) {
	if err := mrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mrc *MedicalRecordCreate) defaults() {
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		v := medicalrecord.DefaultCreatedAt()
		mrc.mutation.SetCreatedAt(v)
	}
	if _, ok := mrc.mutation.UpdatedAt(); !ok {
		v := medicalrecord.DefaultUpdatedAt()
		mrc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mrc.mutation.ID(); !ok {
		v := medicalrecord.DefaultID()
		mrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrc *MedicalRecordCreate) check() error {
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MedicalRecord.created_at"`)}
	}
	if _, ok := mrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MedicalRecord.updated_at"`)}
	}
	return nil
}

func (mrc *MedicalRecordCreate) sqlSave(ctx context.Context) (*MedicalRecord, error) {
	if err := mrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mrc.mutation.id = &_node.ID
	mrc.mutation.done = true
	return _node, nil
}

func (mrc *MedicalRecordCreate) createSpec() (*MedicalRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &MedicalRecord{config: mrc.config}
		_spec = sqlgraph.NewCreateSpec(medicalrecord.Table, sqlgraph.NewFieldSpec(medicalrecord.FieldID, field.TypeUUID))
	)
	if id, ok := mrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mrc.mutation.CreatedAt(); ok {
		_spec.SetField(medicalrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mrc.mutation.UpdatedAt(); ok {
		_spec.SetField(medicalrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mrc.mutation.PatientName(); ok {
		_spec.SetField(medicalrecord.FieldPatientName, field.TypeString, value)
		_node.PatientName = value
	}
	if value, ok := mrc.mutation.PhoneNumber(); ok {
		_spec.SetField(medicalrecord.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := mrc.mutation.Gender(); ok {
		_spec.SetField(medicalrecord.FieldGender, field.TypeInt32, value)
		_node.Gender = value
	}
	if value, ok := mrc.mutation.Age(); ok {
		_spec.SetField(medicalrecord.FieldAge, field.TypeInt32, value)
		_node.Age = value
	}
	if value, ok := mrc.mutation.VisitTime(); ok {
		_spec.SetField(medicalrecord.FieldVisitTime, field.TypeInt64, value)
		_node.VisitTime = value
	}
	if value, ok := mrc.mutation.Diagnosis(); ok {
		_spec.SetField(medicalrecord.FieldDiagnosis, field.TypeString, value)
		_node.Diagnosis = value
	}
	if value, ok := mrc.mutation.TreatmentPlan(); ok {
		_spec.SetField(medicalrecord.FieldTreatmentPlan, field.TypeString, value)
		_node.TreatmentPlan = value
	}
	if value, ok := mrc.mutation.Prescription(); ok {
		_spec.SetField(medicalrecord.FieldPrescription, field.TypeString, value)
		_node.Prescription = value
	}
	if value, ok := mrc.mutation.ExaminationResults(); ok {
		_spec.SetField(medicalrecord.FieldExaminationResults, field.TypeString, value)
		_node.ExaminationResults = value
	}
	if value, ok := mrc.mutation.DoctorAdvice(); ok {
		_spec.SetField(medicalrecord.FieldDoctorAdvice, field.TypeString, value)
		_node.DoctorAdvice = value
	}
	if value, ok := mrc.mutation.DoctorID(); ok {
		_spec.SetField(medicalrecord.FieldDoctorID, field.TypeString, value)
		_node.DoctorID = value
	}
	if value, ok := mrc.mutation.Department(); ok {
		_spec.SetField(medicalrecord.FieldDepartment, field.TypeString, value)
		_node.Department = value
	}
	if value, ok := mrc.mutation.AppointmentID(); ok {
		_spec.SetField(medicalrecord.FieldAppointmentID, field.TypeString, value)
		_node.AppointmentID = value
	}
	if value, ok := mrc.mutation.Remarks(); ok {
		_spec.SetField(medicalrecord.FieldRemarks, field.TypeString, value)
		_node.Remarks = value
	}
	if value, ok := mrc.mutation.UserID(); ok {
		_spec.SetField(medicalrecord.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	return _node, _spec
}

// MedicalRecordCreateBulk is the builder for creating many MedicalRecord entities in bulk.
type MedicalRecordCreateBulk struct {
	config
	err      error
	builders []*MedicalRecordCreate
}

// Save creates the MedicalRecord entities in the database.
func (mrcb *MedicalRecordCreateBulk) Save(ctx context.Context) ([]*MedicalRecord, error) {
	if mrcb.err != nil {
		return nil, mrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mrcb.builders))
	nodes := make([]*MedicalRecord, len(mrcb.builders))
	mutators := make([]Mutator, len(mrcb.builders))
	for i := range mrcb.builders {
		func(i int, root context.Context) {
			builder := mrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MedicalRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mrcb *MedicalRecordCreateBulk) SaveX(ctx context.Context) []*MedicalRecord {
	v, err := mrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrcb *MedicalRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := mrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrcb *MedicalRecordCreateBulk) ExecX(ctx context.Context) {
	if err := mrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
