// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-member-rpc/ent/news"
)

// NewsCreate is the builder for creating a News entity.
type NewsCreate struct {
	config
	mutation *NewsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (nc *NewsCreate) SetCreatedAt(t time.Time) *NewsCreate {
	nc.mutation.SetCreatedAt(t)
	return nc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nc *NewsCreate) SetNillableCreatedAt(t *time.Time) *NewsCreate {
	if t != nil {
		nc.SetCreatedAt(*t)
	}
	return nc
}

// SetUpdatedAt sets the "updated_at" field.
func (nc *NewsCreate) SetUpdatedAt(t time.Time) *NewsCreate {
	nc.mutation.SetUpdatedAt(t)
	return nc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nc *NewsCreate) SetNillableUpdatedAt(t *time.Time) *NewsCreate {
	if t != nil {
		nc.SetUpdatedAt(*t)
	}
	return nc
}

// SetStatus sets the "status" field.
func (nc *NewsCreate) SetStatus(u uint8) *NewsCreate {
	nc.mutation.SetStatus(u)
	return nc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (nc *NewsCreate) SetNillableStatus(u *uint8) *NewsCreate {
	if u != nil {
		nc.SetStatus(*u)
	}
	return nc
}

// SetSort sets the "sort" field.
func (nc *NewsCreate) SetSort(u uint32) *NewsCreate {
	nc.mutation.SetSort(u)
	return nc
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (nc *NewsCreate) SetNillableSort(u *uint32) *NewsCreate {
	if u != nil {
		nc.SetSort(*u)
	}
	return nc
}

// SetTitleZh sets the "title_zh" field.
func (nc *NewsCreate) SetTitleZh(s string) *NewsCreate {
	nc.mutation.SetTitleZh(s)
	return nc
}

// SetNillableTitleZh sets the "title_zh" field if the given value is not nil.
func (nc *NewsCreate) SetNillableTitleZh(s *string) *NewsCreate {
	if s != nil {
		nc.SetTitleZh(*s)
	}
	return nc
}

// SetTitleEn sets the "title_en" field.
func (nc *NewsCreate) SetTitleEn(s string) *NewsCreate {
	nc.mutation.SetTitleEn(s)
	return nc
}

// SetNillableTitleEn sets the "title_en" field if the given value is not nil.
func (nc *NewsCreate) SetNillableTitleEn(s *string) *NewsCreate {
	if s != nil {
		nc.SetTitleEn(*s)
	}
	return nc
}

// SetTitleRu sets the "title_ru" field.
func (nc *NewsCreate) SetTitleRu(s string) *NewsCreate {
	nc.mutation.SetTitleRu(s)
	return nc
}

// SetNillableTitleRu sets the "title_ru" field if the given value is not nil.
func (nc *NewsCreate) SetNillableTitleRu(s *string) *NewsCreate {
	if s != nil {
		nc.SetTitleRu(*s)
	}
	return nc
}

// SetTitleKk sets the "title_kk" field.
func (nc *NewsCreate) SetTitleKk(s string) *NewsCreate {
	nc.mutation.SetTitleKk(s)
	return nc
}

// SetNillableTitleKk sets the "title_kk" field if the given value is not nil.
func (nc *NewsCreate) SetNillableTitleKk(s *string) *NewsCreate {
	if s != nil {
		nc.SetTitleKk(*s)
	}
	return nc
}

// SetContentZh sets the "content_zh" field.
func (nc *NewsCreate) SetContentZh(s string) *NewsCreate {
	nc.mutation.SetContentZh(s)
	return nc
}

// SetNillableContentZh sets the "content_zh" field if the given value is not nil.
func (nc *NewsCreate) SetNillableContentZh(s *string) *NewsCreate {
	if s != nil {
		nc.SetContentZh(*s)
	}
	return nc
}

// SetContentEn sets the "content_en" field.
func (nc *NewsCreate) SetContentEn(s string) *NewsCreate {
	nc.mutation.SetContentEn(s)
	return nc
}

// SetNillableContentEn sets the "content_en" field if the given value is not nil.
func (nc *NewsCreate) SetNillableContentEn(s *string) *NewsCreate {
	if s != nil {
		nc.SetContentEn(*s)
	}
	return nc
}

// SetContentRu sets the "content_ru" field.
func (nc *NewsCreate) SetContentRu(s string) *NewsCreate {
	nc.mutation.SetContentRu(s)
	return nc
}

// SetNillableContentRu sets the "content_ru" field if the given value is not nil.
func (nc *NewsCreate) SetNillableContentRu(s *string) *NewsCreate {
	if s != nil {
		nc.SetContentRu(*s)
	}
	return nc
}

// SetContentKk sets the "content_kk" field.
func (nc *NewsCreate) SetContentKk(s string) *NewsCreate {
	nc.mutation.SetContentKk(s)
	return nc
}

// SetNillableContentKk sets the "content_kk" field if the given value is not nil.
func (nc *NewsCreate) SetNillableContentKk(s *string) *NewsCreate {
	if s != nil {
		nc.SetContentKk(*s)
	}
	return nc
}

// SetCoverURL sets the "cover_url" field.
func (nc *NewsCreate) SetCoverURL(s string) *NewsCreate {
	nc.mutation.SetCoverURL(s)
	return nc
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (nc *NewsCreate) SetNillableCoverURL(s *string) *NewsCreate {
	if s != nil {
		nc.SetCoverURL(*s)
	}
	return nc
}

// SetID sets the "id" field.
func (nc *NewsCreate) SetID(u uint64) *NewsCreate {
	nc.mutation.SetID(u)
	return nc
}

// Mutation returns the NewsMutation object of the builder.
func (nc *NewsCreate) Mutation() *NewsMutation {
	return nc.mutation
}

// Save creates the News in the database.
func (nc *NewsCreate) Save(ctx context.Context) (*News, error) {
	nc.defaults()
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NewsCreate) SaveX(ctx context.Context) *News {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NewsCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NewsCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NewsCreate) defaults() {
	if _, ok := nc.mutation.CreatedAt(); !ok {
		v := news.DefaultCreatedAt()
		nc.mutation.SetCreatedAt(v)
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		v := news.DefaultUpdatedAt()
		nc.mutation.SetUpdatedAt(v)
	}
	if _, ok := nc.mutation.Status(); !ok {
		v := news.DefaultStatus
		nc.mutation.SetStatus(v)
	}
	if _, ok := nc.mutation.Sort(); !ok {
		v := news.DefaultSort
		nc.mutation.SetSort(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NewsCreate) check() error {
	if _, ok := nc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "News.created_at"`)}
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "News.updated_at"`)}
	}
	if _, ok := nc.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "News.sort"`)}
	}
	return nil
}

func (nc *NewsCreate) sqlSave(ctx context.Context) (*News, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NewsCreate) createSpec() (*News, *sqlgraph.CreateSpec) {
	var (
		_node = &News{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(news.Table, sqlgraph.NewFieldSpec(news.FieldID, field.TypeUint64))
	)
	if id, ok := nc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := nc.mutation.CreatedAt(); ok {
		_spec.SetField(news.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := nc.mutation.UpdatedAt(); ok {
		_spec.SetField(news.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := nc.mutation.Status(); ok {
		_spec.SetField(news.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := nc.mutation.Sort(); ok {
		_spec.SetField(news.FieldSort, field.TypeUint32, value)
		_node.Sort = value
	}
	if value, ok := nc.mutation.TitleZh(); ok {
		_spec.SetField(news.FieldTitleZh, field.TypeString, value)
		_node.TitleZh = value
	}
	if value, ok := nc.mutation.TitleEn(); ok {
		_spec.SetField(news.FieldTitleEn, field.TypeString, value)
		_node.TitleEn = value
	}
	if value, ok := nc.mutation.TitleRu(); ok {
		_spec.SetField(news.FieldTitleRu, field.TypeString, value)
		_node.TitleRu = value
	}
	if value, ok := nc.mutation.TitleKk(); ok {
		_spec.SetField(news.FieldTitleKk, field.TypeString, value)
		_node.TitleKk = value
	}
	if value, ok := nc.mutation.ContentZh(); ok {
		_spec.SetField(news.FieldContentZh, field.TypeString, value)
		_node.ContentZh = value
	}
	if value, ok := nc.mutation.ContentEn(); ok {
		_spec.SetField(news.FieldContentEn, field.TypeString, value)
		_node.ContentEn = value
	}
	if value, ok := nc.mutation.ContentRu(); ok {
		_spec.SetField(news.FieldContentRu, field.TypeString, value)
		_node.ContentRu = value
	}
	if value, ok := nc.mutation.ContentKk(); ok {
		_spec.SetField(news.FieldContentKk, field.TypeString, value)
		_node.ContentKk = value
	}
	if value, ok := nc.mutation.CoverURL(); ok {
		_spec.SetField(news.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	return _node, _spec
}

// NewsCreateBulk is the builder for creating many News entities in bulk.
type NewsCreateBulk struct {
	config
	err      error
	builders []*NewsCreate
}

// Save creates the News entities in the database.
func (ncb *NewsCreateBulk) Save(ctx context.Context) ([]*News, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*News, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NewsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NewsCreateBulk) SaveX(ctx context.Context) []*News {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NewsCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NewsCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
