// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilUpdatedAt(value *time.Time) *AppointmentUpdate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *AppointmentUpdateOne {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilUpdatedAt(value *time.Time) *AppointmentCreate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilPatientName(value *string) *AppointmentUpdate {
	if value != nil {
		return a.SetPatientName(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilPatientName(value *string) *AppointmentUpdateOne {
	if value != nil {
		return a.SetPatientName(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilPatientName(value *string) *AppointmentCreate {
	if value != nil {
		return a.SetPatientName(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilPhoneNumber(value *string) *AppointmentUpdate {
	if value != nil {
		return a.SetPhoneNumber(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilPhoneNumber(value *string) *AppointmentUpdateOne {
	if value != nil {
		return a.SetPhoneNumber(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilPhoneNumber(value *string) *AppointmentCreate {
	if value != nil {
		return a.SetPhoneNumber(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilIDCard(value *string) *AppointmentUpdate {
	if value != nil {
		return a.SetIDCard(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilIDCard(value *string) *AppointmentUpdateOne {
	if value != nil {
		return a.SetIDCard(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilIDCard(value *string) *AppointmentCreate {
	if value != nil {
		return a.SetIDCard(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilGender(value *int32) *AppointmentUpdate {
	if value != nil {
		return a.SetGender(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilGender(value *int32) *AppointmentUpdateOne {
	if value != nil {
		return a.SetGender(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilGender(value *int32) *AppointmentCreate {
	if value != nil {
		return a.SetGender(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilAge(value *int32) *AppointmentUpdate {
	if value != nil {
		return a.SetAge(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilAge(value *int32) *AppointmentUpdateOne {
	if value != nil {
		return a.SetAge(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilAge(value *int32) *AppointmentCreate {
	if value != nil {
		return a.SetAge(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilAppointmentTime(value *int64) *AppointmentUpdate {
	if value != nil {
		return a.SetAppointmentTime(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilAppointmentTime(value *int64) *AppointmentUpdateOne {
	if value != nil {
		return a.SetAppointmentTime(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilAppointmentTime(value *int64) *AppointmentCreate {
	if value != nil {
		return a.SetAppointmentTime(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilSymptoms(value *string) *AppointmentUpdate {
	if value != nil {
		return a.SetSymptoms(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilSymptoms(value *string) *AppointmentUpdateOne {
	if value != nil {
		return a.SetSymptoms(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilSymptoms(value *string) *AppointmentCreate {
	if value != nil {
		return a.SetSymptoms(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilStatus(value *int32) *AppointmentUpdate {
	if value != nil {
		return a.SetStatus(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilStatus(value *int32) *AppointmentUpdateOne {
	if value != nil {
		return a.SetStatus(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilStatus(value *int32) *AppointmentCreate {
	if value != nil {
		return a.SetStatus(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilRemarks(value *string) *AppointmentUpdate {
	if value != nil {
		return a.SetRemarks(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilRemarks(value *string) *AppointmentUpdateOne {
	if value != nil {
		return a.SetRemarks(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilRemarks(value *string) *AppointmentCreate {
	if value != nil {
		return a.SetRemarks(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdate) SetNotNilUserID(value *string) *AppointmentUpdate {
	if value != nil {
		return a.SetUserID(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentUpdateOne) SetNotNilUserID(value *string) *AppointmentUpdateOne {
	if value != nil {
		return a.SetUserID(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *AppointmentCreate) SetNotNilUserID(value *string) *AppointmentCreate {
	if value != nil {
		return a.SetUserID(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilUpdatedAt(value *time.Time) *MedicineUpdate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MedicineUpdateOne {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilUpdatedAt(value *time.Time) *MedicineCreate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilStatus(value *uint8) *MedicineUpdate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilStatus(value *uint8) *MedicineUpdateOne {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilStatus(value *uint8) *MedicineCreate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilSort(value *uint32) *MedicineUpdate {
	if value != nil {
		return m.SetSort(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilSort(value *uint32) *MedicineUpdateOne {
	if value != nil {
		return m.SetSort(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilSort(value *uint32) *MedicineCreate {
	if value != nil {
		return m.SetSort(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilName(value *string) *MedicineUpdate {
	if value != nil {
		return m.SetName(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilName(value *string) *MedicineUpdateOne {
	if value != nil {
		return m.SetName(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilName(value *string) *MedicineCreate {
	if value != nil {
		return m.SetName(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilQuantity(value *uint32) *MedicineUpdate {
	if value != nil {
		return m.SetQuantity(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilQuantity(value *uint32) *MedicineUpdateOne {
	if value != nil {
		return m.SetQuantity(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilQuantity(value *uint32) *MedicineCreate {
	if value != nil {
		return m.SetQuantity(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilDescription(value *string) *MedicineUpdate {
	if value != nil {
		return m.SetDescription(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilDescription(value *string) *MedicineUpdateOne {
	if value != nil {
		return m.SetDescription(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilDescription(value *string) *MedicineCreate {
	if value != nil {
		return m.SetDescription(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilRemarks(value *string) *MedicineUpdate {
	if value != nil {
		return m.SetRemarks(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilRemarks(value *string) *MedicineUpdateOne {
	if value != nil {
		return m.SetRemarks(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilRemarks(value *string) *MedicineCreate {
	if value != nil {
		return m.SetRemarks(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdate) SetNotNilImages(value *string) *MedicineUpdate {
	if value != nil {
		return m.SetImages(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineUpdateOne) SetNotNilImages(value *string) *MedicineUpdateOne {
	if value != nil {
		return m.SetImages(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MedicineCreate) SetNotNilImages(value *string) *MedicineCreate {
	if value != nil {
		return m.SetImages(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilUpdatedAt(value *time.Time) *MemberUpdate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MemberUpdateOne {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilUpdatedAt(value *time.Time) *MemberCreate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilStatus(value *uint8) *MemberUpdate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilStatus(value *uint8) *MemberUpdateOne {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilStatus(value *uint8) *MemberCreate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilUsername(value *string) *MemberUpdate {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilUsername(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilUsername(value *string) *MemberCreate {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilPassword(value *string) *MemberUpdate {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilPassword(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilPassword(value *string) *MemberCreate {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilNickname(value *string) *MemberUpdate {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilNickname(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilNickname(value *string) *MemberCreate {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilRankID(value *uint64) *MemberUpdate {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilRankID(value *uint64) *MemberUpdateOne {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilRankID(value *uint64) *MemberCreate {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilMobile(value *string) *MemberUpdate {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilMobile(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilMobile(value *string) *MemberCreate {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilEmail(value *string) *MemberUpdate {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilEmail(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilEmail(value *string) *MemberCreate {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilAvatar(value *string) *MemberUpdate {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilAvatar(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilAvatar(value *string) *MemberCreate {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilWechatOpenID(value *string) *MemberUpdate {
	if value != nil {
		return m.SetWechatOpenID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilWechatOpenID(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetWechatOpenID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilWechatOpenID(value *string) *MemberCreate {
	if value != nil {
		return m.SetWechatOpenID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilExpiredAt(value *time.Time) *MemberUpdate {
	if value != nil {
		return m.SetExpiredAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilExpiredAt(value *time.Time) *MemberUpdateOne {
	if value != nil {
		return m.SetExpiredAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilExpiredAt(value *time.Time) *MemberCreate {
	if value != nil {
		return m.SetExpiredAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilUpdatedAt(value *time.Time) *MemberRankUpdate {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilUpdatedAt(value *time.Time) *MemberRankCreate {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilName(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilName(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilName(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilCode(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilCode(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilCode(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilDescription(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilDescription(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilDescription(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilRemark(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilRemark(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilRemark(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilUpdatedAt(value *time.Time) *NewsUpdate {
	if value != nil {
		return n.SetUpdatedAt(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilUpdatedAt(value *time.Time) *NewsUpdateOne {
	if value != nil {
		return n.SetUpdatedAt(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilUpdatedAt(value *time.Time) *NewsCreate {
	if value != nil {
		return n.SetUpdatedAt(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilStatus(value *uint8) *NewsUpdate {
	if value != nil {
		return n.SetStatus(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilStatus(value *uint8) *NewsUpdateOne {
	if value != nil {
		return n.SetStatus(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilStatus(value *uint8) *NewsCreate {
	if value != nil {
		return n.SetStatus(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilSort(value *uint32) *NewsUpdate {
	if value != nil {
		return n.SetSort(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilSort(value *uint32) *NewsUpdateOne {
	if value != nil {
		return n.SetSort(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilSort(value *uint32) *NewsCreate {
	if value != nil {
		return n.SetSort(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilTitleZh(value *string) *NewsUpdate {
	if value != nil {
		return n.SetTitleZh(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilTitleZh(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetTitleZh(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilTitleZh(value *string) *NewsCreate {
	if value != nil {
		return n.SetTitleZh(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilTitleEn(value *string) *NewsUpdate {
	if value != nil {
		return n.SetTitleEn(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilTitleEn(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetTitleEn(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilTitleEn(value *string) *NewsCreate {
	if value != nil {
		return n.SetTitleEn(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilTitleRu(value *string) *NewsUpdate {
	if value != nil {
		return n.SetTitleRu(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilTitleRu(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetTitleRu(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilTitleRu(value *string) *NewsCreate {
	if value != nil {
		return n.SetTitleRu(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilTitleKk(value *string) *NewsUpdate {
	if value != nil {
		return n.SetTitleKk(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilTitleKk(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetTitleKk(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilTitleKk(value *string) *NewsCreate {
	if value != nil {
		return n.SetTitleKk(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilContentZh(value *string) *NewsUpdate {
	if value != nil {
		return n.SetContentZh(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilContentZh(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetContentZh(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilContentZh(value *string) *NewsCreate {
	if value != nil {
		return n.SetContentZh(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilContentEn(value *string) *NewsUpdate {
	if value != nil {
		return n.SetContentEn(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilContentEn(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetContentEn(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilContentEn(value *string) *NewsCreate {
	if value != nil {
		return n.SetContentEn(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilContentRu(value *string) *NewsUpdate {
	if value != nil {
		return n.SetContentRu(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilContentRu(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetContentRu(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilContentRu(value *string) *NewsCreate {
	if value != nil {
		return n.SetContentRu(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilContentKk(value *string) *NewsUpdate {
	if value != nil {
		return n.SetContentKk(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilContentKk(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetContentKk(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilContentKk(value *string) *NewsCreate {
	if value != nil {
		return n.SetContentKk(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdate) SetNotNilCoverURL(value *string) *NewsUpdate {
	if value != nil {
		return n.SetCoverURL(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsUpdateOne) SetNotNilCoverURL(value *string) *NewsUpdateOne {
	if value != nil {
		return n.SetCoverURL(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (n *NewsCreate) SetNotNilCoverURL(value *string) *NewsCreate {
	if value != nil {
		return n.SetCoverURL(*value)
	}
	return n
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilUpdatedAt(value *time.Time) *OauthProviderUpdate {
	if value != nil {
		return op.SetUpdatedAt(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilUpdatedAt(value *time.Time) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetUpdatedAt(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilUpdatedAt(value *time.Time) *OauthProviderCreate {
	if value != nil {
		return op.SetUpdatedAt(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilName(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetName(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilName(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetName(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilName(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetName(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilClientID(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetClientID(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilClientID(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetClientID(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilClientID(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetClientID(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilClientSecret(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetClientSecret(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilClientSecret(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetClientSecret(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilClientSecret(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetClientSecret(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilRedirectURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetRedirectURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilRedirectURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetRedirectURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilRedirectURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetRedirectURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilScopes(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetScopes(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilScopes(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetScopes(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilScopes(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetScopes(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilAuthURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetAuthURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilAuthURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetAuthURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilAuthURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetAuthURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilTokenURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetTokenURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilTokenURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetTokenURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilTokenURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetTokenURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilAuthStyle(value *uint64) *OauthProviderUpdate {
	if value != nil {
		return op.SetAuthStyle(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilAuthStyle(value *uint64) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetAuthStyle(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilAuthStyle(value *uint64) *OauthProviderCreate {
	if value != nil {
		return op.SetAuthStyle(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilInfoURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetInfoURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilInfoURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetInfoURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilInfoURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetInfoURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilUpdatedAt(value *time.Time) *SwiperUpdate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilUpdatedAt(value *time.Time) *SwiperUpdateOne {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilUpdatedAt(value *time.Time) *SwiperCreate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilStatus(value *uint8) *SwiperUpdate {
	if value != nil {
		return s.SetStatus(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilStatus(value *uint8) *SwiperUpdateOne {
	if value != nil {
		return s.SetStatus(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilStatus(value *uint8) *SwiperCreate {
	if value != nil {
		return s.SetStatus(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilSort(value *uint32) *SwiperUpdate {
	if value != nil {
		return s.SetSort(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilSort(value *uint32) *SwiperUpdateOne {
	if value != nil {
		return s.SetSort(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilSort(value *uint32) *SwiperCreate {
	if value != nil {
		return s.SetSort(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilTitleZh(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetTitleZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilTitleZh(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetTitleZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilTitleZh(value *string) *SwiperCreate {
	if value != nil {
		return s.SetTitleZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilTitleEn(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetTitleEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilTitleEn(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetTitleEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilTitleEn(value *string) *SwiperCreate {
	if value != nil {
		return s.SetTitleEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilTitleRu(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetTitleRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilTitleRu(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetTitleRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilTitleRu(value *string) *SwiperCreate {
	if value != nil {
		return s.SetTitleRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilTitleKk(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetTitleKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilTitleKk(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetTitleKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilTitleKk(value *string) *SwiperCreate {
	if value != nil {
		return s.SetTitleKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilBannerZh(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetBannerZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilBannerZh(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetBannerZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilBannerZh(value *string) *SwiperCreate {
	if value != nil {
		return s.SetBannerZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilBannerEn(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetBannerEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilBannerEn(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetBannerEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilBannerEn(value *string) *SwiperCreate {
	if value != nil {
		return s.SetBannerEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilBannerRu(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetBannerRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilBannerRu(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetBannerRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilBannerRu(value *string) *SwiperCreate {
	if value != nil {
		return s.SetBannerRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilBannerKk(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetBannerKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilBannerKk(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetBannerKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilBannerKk(value *string) *SwiperCreate {
	if value != nil {
		return s.SetBannerKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilContentZh(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetContentZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilContentZh(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetContentZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilContentZh(value *string) *SwiperCreate {
	if value != nil {
		return s.SetContentZh(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilContentEn(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetContentEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilContentEn(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetContentEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilContentEn(value *string) *SwiperCreate {
	if value != nil {
		return s.SetContentEn(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilContentRu(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetContentRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilContentRu(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetContentRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilContentRu(value *string) *SwiperCreate {
	if value != nil {
		return s.SetContentRu(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilContentKk(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetContentKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilContentKk(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetContentKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilContentKk(value *string) *SwiperCreate {
	if value != nil {
		return s.SetContentKk(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdate) SetNotNilJumpURL(value *string) *SwiperUpdate {
	if value != nil {
		return s.SetJumpURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperUpdateOne) SetNotNilJumpURL(value *string) *SwiperUpdateOne {
	if value != nil {
		return s.SetJumpURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *SwiperCreate) SetNotNilJumpURL(value *string) *SwiperCreate {
	if value != nil {
		return s.SetJumpURL(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilUpdatedAt(value *time.Time) *TokenUpdate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilUpdatedAt(value *time.Time) *TokenUpdateOne {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilUpdatedAt(value *time.Time) *TokenCreate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilStatus(value *uint8) *TokenUpdate {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilStatus(value *uint8) *TokenUpdateOne {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilStatus(value *uint8) *TokenCreate {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilUUID(value *uuid.UUID) *TokenUpdate {
	if value != nil {
		return t.SetUUID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilUUID(value *uuid.UUID) *TokenUpdateOne {
	if value != nil {
		return t.SetUUID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilUUID(value *uuid.UUID) *TokenCreate {
	if value != nil {
		return t.SetUUID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilToken(value *string) *TokenUpdate {
	if value != nil {
		return t.SetToken(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilToken(value *string) *TokenUpdateOne {
	if value != nil {
		return t.SetToken(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilToken(value *string) *TokenCreate {
	if value != nil {
		return t.SetToken(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilUsername(value *string) *TokenUpdate {
	if value != nil {
		return t.SetUsername(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilUsername(value *string) *TokenUpdateOne {
	if value != nil {
		return t.SetUsername(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilUsername(value *string) *TokenCreate {
	if value != nil {
		return t.SetUsername(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilSource(value *string) *TokenUpdate {
	if value != nil {
		return t.SetSource(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilSource(value *string) *TokenUpdateOne {
	if value != nil {
		return t.SetSource(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilSource(value *string) *TokenCreate {
	if value != nil {
		return t.SetSource(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilExpiredAt(value *time.Time) *TokenUpdate {
	if value != nil {
		return t.SetExpiredAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilExpiredAt(value *time.Time) *TokenUpdateOne {
	if value != nil {
		return t.SetExpiredAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilExpiredAt(value *time.Time) *TokenCreate {
	if value != nil {
		return t.SetExpiredAt(*value)
	}
	return t
}
